version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.12

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            pytest --maxfail=1 --disable-warnings -v

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
